name: Bump Tag

on:
  workflow_call:
    outputs:
      bumped-tag:
        description: The bumped tag.
        value: ${{ jobs.bump-tag.outputs.bumped-tag }}
jobs:
  bump-tag:
    name: Bump Tag
    runs-on: ubuntu-latest
    outputs:
      bumped-tag: ${{ steps.auto-tag.outputs.bumped-tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Install AutoTag
        run: curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/bin
      - name: Run AutoTag
        id: auto-tag
        run: echo "::set-output name=bumped-tag::v$(autotag -n)"
